apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base/

images:
- name: gcr.io/heptio-images/ks-guestbook-demo
  newTag: "0.2"

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: guestbook-ui
  path: image-patch.yaml
